import assert from "node:assert/strict";
import fs from "node:fs";
import test from "node:test";

const appSource = fs.readFileSync(new URL("../web/src/App.tsx", import.meta.url), "utf8");
const serverSource = fs.readFileSync(new URL("../src/server.mjs", import.meta.url), "utf8");

test("the React workspace exposes Stripe connection status and invoice history", () => {
  assert.match(appSource, /\["payments", "Payments"\], \["ai-usage", "AI Usage"\]/);
  assert.match(appSource, /function PaymentsScreen\(\)/);
  assert.match(appSource, /useApi<\{ stripe: StripeConnectionStatus \}>\("\/api\/payments\/stripe\/status"\)/);
  assert.match(appSource, /api<\{ url: string \}>\("\/api\/payments\/stripe\/oauth\/start", \{ method: "POST" \}\)/);
  assert.match(appSource, /window\.location\.assign\(result\.url\)/);
  assert.match(appSource, /useApi<\{ count: number; invoices: Entity\[\] \}>\("\/api\/payment-invoices\?limit=100"\)/);
  assert.match(appSource, /Due \{formatLocalDate\(textKey\(invoice, "dueOn"\)\)\}/);
  assert.match(appSource, /Open Stripe/);
  assert.match(appSource, /function InvoiceEditor\(/);
  assert.match(appSource, /View invoice/);
  assert.match(appSource, /Save changes/);
  assert.match(appSource, /Add line/);
  assert.match(appSource, /New manual line/);
  assert.match(appSource, /removeNewLine/);
  assert.match(appSource, /method: "PATCH"/);
  assert.match(appSource, /previewDigest: textKey\(invoice, "previewDigest"\)/);
  assert.match(appSource, /paymentMethodPolicy/);
  assert.match(appSource, /Bank account only \(no credit cards\)/);
  assert.match(appSource, /Credit card and bank account/);
  assert.match(appSource, /Yes, send invoice/);
  assert.match(appSource, /\/api\/payment-invoices\/\$\{invoiceId\}\/send/);
  assert.match(appSource, /Save your line changes before sending this invoice/);
  assert.match(appSource, /invoice-history-list/);
  assert.match(appSource, /Newest first/);
  assert.match(appSource, /rightCreated - leftCreated/);
  assert.match(appSource, /Open PDF/);
  assert.match(appSource, /\/api\/payment-invoices\/\$\{invoiceId\}\/pdf/);
  assert.match(serverSource, /request\.method === "PATCH" && paymentInvoiceMatch/);
  assert.match(serverSource, /payments\.updatePreparedInvoice/);
  assert.match(serverSource, /request\.method === "POST" && paymentInvoiceSendMatch/);
  assert.match(serverSource, /payments\.sendInvoice/);
  assert.match(serverSource, /request\.method === "GET" && paymentInvoicePdfMatch/);
  assert.match(serverSource, /payments\.invoicePdf/);
});
